### PR TITLE
In this file Sequence is not typing.Sequence

### PR DESCRIPTION
**Pull request by euresti**
Hi.  I started testing this against our codebase and noticed some errors.

### CODE REVIEW

**Comment by bryanforbes** [comment]
Yes, this was an oversight on my part. Good find @euresti!

@ilevkivskyi does he need to sign a CLA?

**Comment by ilevkivskyi** [comment]
Oh, yes, indeed I completely forgot about [CLA](https://opensource.dropbox.com/cla/), @euresti could you please sign it?

**Comment by euresti** [comment]
Done!

**Comment by ilevkivskyi** [comment]
Thanks for signing CLA! Are you going to add the test as I suggested above? (If not, I will merge this anyway, but it is always better with a test.)

**Comment by euresti** [comment]
I'll look into a test. I was testing this on our code base and found a couple of other issues with the stubs. I'll file Issues for those since I'm not sure what the correct solution to some of those are.

**Comment by euresti** [comment]
Test has been added.

**Comment by ilevkivskyi** [comment]
Thanks!

**Comment by ilevkivskyi** [comment]
> I was testing this on our code base and found a couple of other issues with the stubs. I'll file Issues for those since I'm not sure what the correct solution to some of those are.

OK, sure.

**Pull request merged**
