### PR TITLE
Fix incompatibility with the latest typeshed stubs

### PR DESCRIPTION
**Pull request by JukkaL**
`__hash__` in `set` is now defined as `None`.

### CODE REVIEW

**Comment by bryanforbes** [comment]
Is there any way to get this into a new release? 0.2 isn't usable with mypy 0.740

**Comment by ilevkivskyi** [comment]
OK, I will try to prepare 0.3 next week (no guarantees however).

**Comment by bryanforbes** [comment]
Sounds good! Thanks for the work on this!

**Comment by ilevkivskyi** [comment]
@bryanforbes 
Current master causes some errors in our internal repos, I will try fixing them, and then will proceed with the release (the mypy API compatibility issues are now fixed, so we are almost ready for the release).

**Comment by ilevkivskyi** [comment]
@bryanforbes `sqlalchemy-stubs 0.3` is out on PyPI, try it out!

**Comment by bryanforbes** [comment]
@ilevkivskyi I just bumped my project to use it and it works great. Thanks!!

**Pull request merged**
