### PR TITLE
Fixes/is operator and jsonb

### PR DESCRIPTION
**Pull request by Pavkazzz**

### CODE REVIEW

**Comment by Pavkazzz** [comment]
Fix: https://github.com/dropbox/sqlalchemy-stubs/issues/207

**Comment by moui72** [comment]
please merge! :D

**Comment by jhirshman** [comment]
I have a PR up that does something similar:
https://github.com/dropbox/sqlalchemy-stubs/pull/211

It hasn't been merged in a while.

**Comment by Pavkazzz** [comment]
@jhirshman i suppose you mean #202.
Maybe we should fork and upload it to pypi, while dropbox doesn't maintain this package?

**Comment by jhirshman** [comment]
> @jhirshman i suppose you mean #202.
> Maybe we should fork and upload it to pypi, while dropbox doesn't maintain this package?

yes, sorry. I linked to the wrong one.

I agree that forking it might be the right solution here.

**Comment by peterschutt** [comment]
If you haven’t already seen, check out the more recent activity on [this issue](https://github.com/dropbox/sqlalchemy-stubs/issues/195) and [this issue](https://github.com/sqlalchemy/sqlalchemy/issues/4609). 

It seems as though we are fortunate enough that Mike has turned his attention to having typing integration with sqla 1.4/2.0.

I mention this as it might change your opinion as to the need to fork the repo.

**Pull request closed without merging**
