### PR TITLE
Add more selectable typings

### PR DESCRIPTION
**Pull request by bryanforbes**

### CODE REVIEW

**Comment by ilevkivskyi** [comment]
Sorry for a delay, I just tried this again. There are still three errors in our codebase:
* One is `Argument 1 to "insert" of "TableClause" has incompatible type "Dict[Column[Any], int]"; expected "Optional[Mapping[Union[str, ColumnClause[Any]], Any]]"`. This because `Mapping` is invariant in key. You probably need to use a huge union here: `Union[None, Mapping[str, Any], Mapping[ColumnClause[Any], Any], Mapping[Union[str, ColumnClause[Any]], Any]]`
* Another is `Argument "order_by" to "Select" has incompatible type "Sequence[SortOrder]"; expected "Optional[Iterable[Union[int, str, Visitable]]]"`
* Finally, there is `Argument 3 to "Select" has incompatible type "Table"; expected "Optional[Iterable[Union[str, Selectable]]]"` similar to the one appeared with the previous version of the PR (argument 3 is `from_obj`)

As for tests, the easiest way is to just add dummy tests for affected constructors calls/method calls as I suggested on Gitter.

**Comment by ilevkivskyi** [comment]
(Also an unrelated thought about speeding things up, I think I can manage to review/try PRs twice as large as this one, so if it is OK for you, I think we can try larger sizes.)

**Comment by bryanforbes** [comment]
>     * Another is `Argument "order_by" to "Select" has incompatible type "Sequence[SortOrder]"; expected "Optional[Iterable[Union[int, str, Visitable]]]"`

Is it a bug in `typeshed` that `Sequence` doesn't inherit from `Iterable`?

**Comment by bryanforbes** [comment]
I just looked. `Iterable` is a `Protocol`, so `Sequence` should match `Iterable`. What is `SortOrder` in your code?

**Comment by ilevkivskyi** [comment]
Oh, sorry, ignore this one. This is a real bug in our codebase found by your new types. :-)

**Comment by ilevkivskyi** [comment]
@bryanforbes what is the status of this PR? Is any input from my side needed?

**Comment by bryanforbes** [comment]
@ilevkivskyi No input needed. I just need to put together some tests for the issues you found. I'll try to do that over the weekend or early next week.

**Comment by ilevkivskyi** [comment]
Great, thanks!

**Comment by bryanforbes** [comment]
I added a bunch of unit tests testing the issues your found, but I ran into a new issue:

```python
t = table('user', column('id'), column('name'), column('description'), column('articles'))
t.insert({column('name', String): 'foo',
          'description': 'bar'})
```

mypy infers the type of the argument to `insert()` as `Dict[object, str]` instead of `Dict[Union[ColumnClause[Any], str], str]`. Once that is solved, I think we can merge this.

**Comment by ilevkivskyi** [comment]
Thanks for an update and for good tests!

I think the problem you encountered is not easy to fix. It looks like there is a mypy bug (or missing feature) here. Basically mypy's type inference sometimes misfires in presence of unions. I would just remove this particular line in your tests, and open an issue on mypy tracker (maybe also try to find a simpler repro), and then I merge this PR.

**Comment by bryanforbes** [comment]
I commented out the failing invocation. I agree that this is either a bug or a missing feature of mypy. A simple repro is as follows:

```python
d = {'1': 2, 3: 4}
reveal_type(d)  # builtins.dict[builtins.object*, builtins.int*]
```

I have filed an issue at python/mypy#6079.

**Comment by ilevkivskyi** [comment]
OK, thanks!

**Pull request merged**
