### PR TITLE
Basic type information & alphabetical sorting

### PR DESCRIPTION
**Pull request by sollyucko**
Added some basic type information (mainly return types of generative methods); sorted methods alphabetically

### CODE REVIEW

**Comment by ilevkivskyi** [comment]
Thanks for PR! Before I proceed with the full review I have two short questions:
1. Have you signed the CLA mentioned in README?
2. Is the alphabetic ordering really necessary? I think typeshed uses the style where order of definitions match the order at runtime, we want to match the style of typeshed as much as possible.

**Comment by sollyucko** [comment]
1. Oops, I forgot to check for that sort of thing. Do you know why a mailing address is necessary?
2. I was having trouble matching up the original definitions with the typed definitions, especially since the semi-alphabetization was throwing me off. Good point, though.

**Comment by ilevkivskyi** [comment]
TBH, I have no idea why the address is needed (definitely _not_ to send you spam :-). Anyway, Dropbox has high privacy standards (you can find a link in the CLA form) so I would not worry it will be used in inappropriate way.

**Comment by sollyucko** [comment]
Actually, given that it would probably be easier to just to recreate the type annotations than to undo my mistaken alphabetization, I'm just going to close this PR. Someone with a bit more SQLAlchemy expertise could probably add these in along with basic typing for the rest.

**Comment by sollyucko** [comment]
BTW, most of what I did is add return types to the methods decorated with `_generative`.

**Pull request closed without merging**
