### PR TITLE
Fix default type for Numeric columns to Decimal

### PR DESCRIPTION
**Pull request by martinstein**
Here's the very simple PR as discussed in #131 . Longer term it would probably be nice to have an approach that knows about the different types depending on the `asdecimal` parameter. But for now this should already help.

### CODE REVIEW

**Comment by raychan** [comment]
What is the plan to release this fix. Thank you

**Comment by nick-bigger** [comment]
Any word on when this will be released?

**Comment by jneves** [comment]
Just FYI it's now on sqlalchemy-stubs-dev package if needed.

**Comment by hippoandy** [comment]
> Just FYI it's now on sqlalchemy-stubs-dev package if needed.

Hi @jneves is there a timeline that this fix will be available for a stable release? Thank you!

**Pull request merged**
